### ISSUE TITLE
'stack ghci' has errors in REPL

### ISSUE THREAD

**Issue by Hodapp87** [GaloisInc/ivory#56]
I have been using Ivory on [Stack](https://github.com/commercialhaskell/stack) and, while the build has been working just fine, I find I am unable to get to a REPL with 'stack ghci'.

I brought this issue up with some Stack developers and was told I should bring it up here. My stack.yaml is:

```yaml
flags: {}
packages:
- ivory-stdlib/
- ivory-model-check/
- ivory-opts/
- ivory-examples/
- ivory-backend-acl2/
- ivory-serialize/
- ivory/
- ivory-hw/
- ivory-eval/
- ivory-backend-c/
- ivory-quickcheck/
- ivory-artifact/
extra-deps:
- acl2-0.0.1
- ghc-srcspan-plugin-0.2.1.0
resolver: lts-2.21
```

and I have been running 'stack test' and 'stack ghci'. The latter eventually fails with:

```
There were multiple candidates for the Cabal entry "Test.hs(/home/hodapp/source/ivory/ivory-examples/examples/Test.hs), pi
cking /home/hodapp/source/ivory/ivory-model-check/test/Test.hs
Configuring GHCi with the following packages: ivory-artifact, ivory-backend-acl2, ivory-backend-c, ivory-eval, ivory-examp
les, ivory-hw, ivory-model-check, ivory-opts, ivory-quickcheck, ivory-serialize, ivory-stdlib, ivory
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package bytestring-0.10.4.0 ... linking ... done.
Loading package filepath-1.3.0.2 ... linking ... done.
... (removed a bunch of lines) ...
Loading package acl2-0.0.1 ... linking ... done.
Loading package monadLib-3.7.3 ... linking ... done.
Loading package blaze-builder-0.4.0.1 ... linking ... done.
Loading package unordered-containers-0.2.5.1 ... linking ... done.
Loading package semigroups-0.16.2.2 ... linking ... done.
Loading package void-0.7 ... linking ... done.
Loading package HStringTemplate-0.8.3 ... linking ... done.
Loading package utf8-string-1 ... linking ... done.
Warning: ignoring unrecognised input `/home/hodapp/source/ivory/ivory/src/Ivory/Language/Syntax/Concrete/Lexer.x'
Warning: ignoring unrecognised input `/home/hodapp/source/ivory/ivory/src/Ivory/Language/Syntax/Concrete/Parser.y'

/home/hodapp/source/ivory/ivory/src/Ivory/Language/Syntax/Concrete/QQ.hs:45:8:
    Could not find module ‘Ivory.Language.Syntax.Concrete.Lexer’
    It is a member of the hidden package ‘ivory-0.1.0.2’.
    Use -v to see a list of the files searched for.

/home/hodapp/source/ivory/ivory/src/Ivory/Language/Syntax/Concrete/QQ.hs:46:18:
    Could not find module ‘Ivory.Language.Syntax.Concrete.Parser’
    It is a member of the hidden package ‘ivory-0.1.0.2’.
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
Prelude> 
```

And if I try to import Ivory.Language:

```
Prelude> import Ivory.Language

<no location info>:
    Could not find module ‘Ivory.Language’
    It is a member of the hidden package ‘ivory-0.1.0.2’.
```

This is a pretty minor issue (I can still just run a REPL in the cabal sandbox), and I may look into it myself, but I figured I would post it here in case anyone can shed some light on the problem.

**Comment by gridaphobe** [comment]
```
Warning: ignoring unrecognised input `/home/hodapp/source/ivory/ivory/src/Ivory/Language/Syntax/Concrete/Lexer.x'
Warning: ignoring unrecognised input `/home/hodapp/source/ivory/ivory/src/Ivory/Language/Syntax/Concrete/Parser.y'
```

You probably need to use `cabal repl` (or manually run happy and alex to generate the parser). I suspect `stack ghci` has a flag that would tell it to start a `cabal repl` instead of a plain `ghci`, but I've never used stack personally.

**Comment by pchickey** [comment]
We haven't tried using stack for building any Ivory related code, so unfortunately I can't offer any help with this. If you do figure out how to get it to work, we'd appreciate hearing your results, and we would accept any patches required.

**Comment by Hodapp87** [comment]
Sure, @pchickey. I can tell you that Ivory already builds just fine in stack and various different resolvers (and if I get past this issue, I'll commit the stack.yaml that I use), but I'm not sure if the tests run right, and that might be related.

**Comment by bitemyapp** [comment]
@Hodapp87 @pchickey having tested `language-python`, it appears the Cabal file for `ivory` is incomplete.

Contrast with https://github.com/bjpop/language-python/blob/master/language-python.cabal

Cf. http://stackoverflow.com/questions/32899040/how-can-i-make-stack-call-happy-alex-and-other-build-tools

This should rectify it, ping me if it doesn't. I couldn't completely test it with language-python because my machine is overloaded at the moment.

**Comment by Hodapp87** [comment]
@bitemyapp, this seems to get further, but develops other problems (I stuck a log of the latest one in https://raw.githubusercontent.com/Hodapp87/ivory/stack-ghci/ivory-wtf.txt). This may be related to https://github.com/commercialhaskell/stack/issues/970.

**Comment by tinkyholloway** [comment]
Using the `stack.yaml` from @Hodapp87 as a starting point, I was able to build a project with `stack` and use `ghci`. Below is my `stack.yaml`. I need to first
````bash
$ stack install happy
$ stack install alex
````
then
```` bash
$ stack build
````
watch a lot of warnings about the changes to the `Prelude` re `Applicative` and `Monoid`, and then
````bash
$ stack ghci <projectname>:exe:<executablename>
````
Here is my `stack.yaml`:
````yaml
flags: {}
packages:
- '.'
- location:
    git: https://github.com/GaloisInc/ivory.git
    commit: 7ecea5839898b65430ca298fd1f3af4d2272e3fb
  subdirs:
  - ivory-artifact
  - ivory-backend-c
  - ivory-eval
  - ivory-examples
  - ivory-hw
  - ivory-model-check
  - ivory-opts
  - ivory-quickcheck
  - ivory-serialize
  - ivory-stdlib
  - ivory
extra-deps:
- happy-1.19.5
- alex-3.1.4
- ghc-srcspan-plugin-0.2.1.0
````
